spring:
  #Redis相关配置
  redis:
    # 指定库
    database: 5
    host: 39.105.164.67
    port: 6379
    password: root
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 100
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 10
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000